### ISSUE TITLE
tons of unnecessary output in cout stream from CCAL shower code And then CRASH

### ISSUE THREAD

**Issue by zihlmann** [JeffersonLab/halld_recon#125]
Below is the output and the crash: (the analysis was done on run 61343 asking for CCALShower)
.......
 case 0 ch
 case 0 ch
 case 0 ch
 case 0 ch
 case 0 ch
 case 0 ch
 case 0 ch
 case 0 ch
 case 0 ch
 case 0 ch
hd_root: libraries/CCAL/DCCALGeometry.cc:83: DVector2 DCCALGeometry::positionOnFace(int) const: Assertion `channel >= 0 && channel < m_numActiveBlocks' failed.
Abort

**Comment by sdobbs** [comment]
Were you running multithreaded?

On Thu, Feb 28, 2019 at 2:22 PM zihlmann <notifications@github.com<mailto:notifications@github.com>> wrote:

Below is the output and the crash: (the analysis was done on run 61343 asking for CCALShower)
.......
case 0 ch
case 0 ch
case 0 ch
case 0 ch
case 0 ch
case 0 ch
case 0 ch
case 0 ch
case 0 ch
case 0 ch
hd_root: libraries/CCAL/DCCALGeometry.cc:83: DVector2 DCCALGeometry::positionOnFace(int) const: Assertion `channel >= 0 && channel < m_numActiveBlocks' failed.
Abort

**Comment by zihlmann** [comment]
Yes I was! I just now run in single thread mode and things seem to look better.

**Comment by sdobbs** [comment]
Yes, multithreading doesn't work with CCAL reconstruction [yet]...
Someone does need to clean up the print outs, though.

**Comment by sdobbs** [comment]
Are these printouts still showing up for you?

**Comment by sdobbs** [comment]
unnecessary printouts seem to be reduced, closing
