### ISSUE TITLE
occupancy_online plugin crash

### ISSUE THREAD

**Issue by aaust** [JeffersonLab/halld_recon#151]
after merging pull request #147 , the occupancy_online plugin produces a crash in line 340:

```
if( !((l1trigger->fp_trig_mask & 0x100) || (l1trigger->fp_trig_mask & 0x200)) 
&& (total_bcal_energy < 20.) ) {
```

**Comment by sdobbs** [comment]
Which file did this crash happen with?  I was not immediately able to reproduce this with the following file:
/cache/halld/RunPeriod-2019-01/rawdata/Run061879/hd_rawdata_061879_001.evio

On Wed, Apr 10, 2019 at 9:12 AM Alex Austregesilo <notifications@github.com<mailto:notifications@github.com>> wrote:

after merging pull request #147<https://github.com/JeffersonLab/halld_recon/pull/147> , the occupancy_online plugin produces a crash in line 340:

if( !((l1trigger->fp_trig_mask & 0x100) || (l1trigger->fp_trig_mask & 0x200))
&& (total_bcal_energy < 20.) ) {

**Comment by aaust** [comment]
I saw the crash with the 000 file. Some events do not have a l1trigger.

Pull request #152 should fit it.

**Comment by sdobbs** [comment]
OK, thanks!
