### ISSUE TITLE
Request for hd_root to check for input file existence before trying to open it

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/halld_recon#436]
At present it hangs.  (I think it used to segfault.)

**Comment by sdobbs** [comment]
Actually, I think that the root cause of the hanging is the same as in #418 - otherwise if the input file is missing, it will print an error message (or used to in some older versions)

**Comment by nsjarvis** [comment]
[I fixed it. ](https://github.com/JeffersonLab/halld_recon/pull/487)
