### ISSUE TITLE
memory blow up

### ISSUE THREAD

**Issue by zihlmann** [JeffersonLab/halld_recon#745]
when analyzing a file from run 81421 using the plugin HLDetectorTiming the memory usage of hd_root starts climbing and climbing
till on the batch farm the job eventually will fail due to SLURM_OUT_OF_MEMORY

If I do not include  the plugin HLDetectorTiming and only use my plugin then this does not happen. The memory usage still shows
a slight increase with running time but never as much as with the plugin HLDetectorTiming.

It turns out that run 81421 is with Solenoid field OFF. In fact the above behavior can be seen with any run from the PrimeX run time
where the magnetic field was OFF.
Note that 
ccdb dump Magnets/Solenoid/solenoid_map:81421
#Set by hand
  NoField     

is correctly set as it should.

**Comment by sdobbs** [comment]
@zihlmann - just checking, did you pass any command line flags to HLDetectorTiming ?  or just the defaults?

**Comment by sdobbs** [comment]
and how much memory are you requesting for your jobs?

**Comment by zihlmann** [comment]
I started with the 4GB that works for all other jobs/runs. And then I 
gradually increased
to 12GB I think and it sill crashed.

On 9/27/23 10:55, Sean Dobbs wrote:
>
> and how much memory are you requesting for your jobs?
>
> —
> Reply to this email directly, view it on GitHub 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JeffersonLab_halld-5Frecon_issues_745-23issuecomment-2D1737569073&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=Hy7ijcc6pcMoP-QxZxtQH4-vodW_VGkrA9xiBc7InXk&m=MPOfhlAS7Rvbk3UvvG9zdpc_iWGeY_zSeuc_sKAu4-MEz4Y9hj0K-uUVNnNQctVk&s=gB27ft2AyBtQQKB77XRnAdEB49If1eX9BPTDB0254GM&e=>, 
> or unsubscribe 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADF7AC2OTNADDQSNWCJJM23X4Q46XANCNFSM6AAAAAA4NPGYC4&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=Hy7ijcc6pcMoP-QxZxtQH4-vodW_VGkrA9xiBc7InXk&m=MPOfhlAS7Rvbk3UvvG9zdpc_iWGeY_zSeuc_sKAu4-MEz4Y9hj0K-uUVNnNQctVk&s=XXnGuk2zvTlIYQP4f1ok8gMfkUyfmXZUcew-DaHT9nE&e=>.
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>
>

--------------3m9h8Jf6aHJS5a1XZQa6W8zz
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit

<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
    I started with the 4GB that works for all other jobs/runs. And then
    I gradually increased<br>
    to 12GB I think and it sill crashed.<br>
    <br>
    <div class="moz-cite-prefix">On 9/27/23 10:55, Sean Dobbs wrote:<br>
    </div>
    <blockquote type="cite" ***@***.***">
      
      <p dir="auto">and how much memory are you requesting for your
        jobs?</p>
      <p style="font-size:small;-webkit-text-size-adjust:none;color:#666;">—<br>
        Reply to this email directly, <a href="https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JeffersonLab_halld-5Frecon_issues_745-23issuecomment-2D1737569073&amp;d=DwMCaQ&amp;c=CJqEzB1piLOyyvZjb8YUQw&amp;r=Hy7ijcc6pcMoP-QxZxtQH4-vodW_VGkrA9xiBc7InXk&amp;m=MPOfhlAS7Rvbk3UvvG9zdpc_iWGeY_zSeuc_sKAu4-MEz4Y9hj0K-uUVNnNQctVk&amp;s=gB27ft2AyBtQQKB77XRnAdEB49If1eX9BPTDB0254GM&amp;e=" moz-do-not-send="true">view it on GitHub</a>, or <a href="https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADF7AC2OTNADDQSNWCJJM23X4Q46XANCNFSM6AAAAAA4NPGYC4&amp;d=DwMCaQ&amp;c=CJqEzB1piLOyyvZjb8YUQw&amp;r=Hy7ijcc6pcMoP-QxZxtQH4-vodW_VGkrA9xiBc7InXk&amp;m=MPOfhlAS7Rvbk3UvvG9zdpc_iWGeY_zSeuc_sKAu4-MEz4Y9hj0K-uUVNnNQctVk&amp;s=XXnGuk2zvTlIYQP4f1ok8gMfkUyfmXZUcew-DaHT9nE&amp;e=" moz-do-not-send="true">unsubscribe</a>.<br>
        You are receiving this because you were mentioned.<img src="https://github.com/notifications/beacon/ADF7AC52NSYHXGUDJIC6XKTX4Q46XA5CNFSM6AAAAAA4NPGYC6WGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTHSEZTC.gif" alt="" moz-do-not-send="true" width="1" height="1"><span style="color: transparent; font-size: 0; display: none;
          visibility: hidden; overflow: hidden; opacity: 0; width: 0;
          height: 0; max-width: 0; max-height: 0; mso-hide: all">Message
          ID: <span>&lt;JeffersonLab/halld_recon/issues/745/1737569073</span><span>@</span><span>github</span><span>.</span><span>com&gt;</span></span></p>
      <script type="application/ld+json">[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/JeffersonLab/halld_recon/issues/745#issuecomment-1737569073",
"url": "https://github.com/JeffersonLab/halld_recon/issues/745#issuecomment-1737569073",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]</script>
    </blockquote>
    <br>
  </body>
</html>

--------------3m9h8Jf6aHJS5a1XZQa6W8zz--

**Comment by sdobbs** [comment]
running on the command-line, I'm seeing the jobs peak at 5-6 GB for 8 threads, which is not out of the expectation from what I see running other standard plugins, like danarest and monitoring_hists.  That's not to say that there's nothing wrong with the memory usage - but I'm not seeing anything excessive like that.  Was there a particular file this was happening to, or was it for all of the runs?

**Comment by zihlmann** [comment]
as mentioned in the start of this thread my observation was that it 
happens only for run where the solenoid field was off  so for example 
run 81421

On 9/27/23 11:06, Sean Dobbs wrote:
>
> running on the command-line, I'm seeing the jobs peak at 5-6 GB for 8 
> threads, which is not out of the expectation from what I see running 
> other standard plugins, like danarest and monitoring_hists. That's not 
> to say that there's nothing wrong with the memory usage - but I'm not 
> seeing anything excessive like that. Was there a particular file this 
> was happening to, or was it for all of the runs?
>
> —
> Reply to this email directly, view it on GitHub 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JeffersonLab_halld-5Frecon_issues_745-23issuecomment-2D1737589965&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=Hy7ijcc6pcMoP-QxZxtQH4-vodW_VGkrA9xiBc7InXk&m=8Z3owTVaNZCsWPb8_BP8F5tA7zcWi2LG3nMX-nwDTaaYQxtr_MKPuwKF9hujYlqU&s=CmuQQvtCNHbWn7X9Zrjsrz92UDnyruY-lGkzJX9j4gE&e=>, 
> or unsubscribe 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADF7AC2RO5ZLEGLEJJJUAMDX4Q6IHANCNFSM6AAAAAA4NPGYC4&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=Hy7ijcc6pcMoP-QxZxtQH4-vodW_VGkrA9xiBc7InXk&m=8Z3owTVaNZCsWPb8_BP8F5tA7zcWi2LG3nMX-nwDTaaYQxtr_MKPuwKF9hujYlqU&s=qhnn74Z8lOGQS9yYc5qNrZt92fPpYwnoL8KImGAsbl8&e=>.
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>
>

--------------C6tMp2h70xLCNEf6PvGmpYpA
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit

<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
    as mentioned in the start of this thread my observation was that it
    happens only for run where the solenoid field was off&nbsp; so for
    example run 81421<br>
    <br>
    <div class="moz-cite-prefix">On 9/27/23 11:06, Sean Dobbs wrote:<br>
    </div>
    <blockquote type="cite" ***@***.***">
      
      <p dir="auto">running on the command-line, I'm seeing the jobs
        peak at 5-6 GB for 8 threads, which is not out of the
        expectation from what I see running other standard plugins, like
        danarest and monitoring_hists. That's not to say that there's
        nothing wrong with the memory usage - but I'm not seeing
        anything excessive like that. Was there a particular file this
        was happening to, or was it for all of the runs?</p>
      <p style="font-size:small;-webkit-text-size-adjust:none;color:#666;">—<br>
        Reply to this email directly, <a href="https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JeffersonLab_halld-5Frecon_issues_745-23issuecomment-2D1737589965&amp;d=DwMCaQ&amp;c=CJqEzB1piLOyyvZjb8YUQw&amp;r=Hy7ijcc6pcMoP-QxZxtQH4-vodW_VGkrA9xiBc7InXk&amp;m=8Z3owTVaNZCsWPb8_BP8F5tA7zcWi2LG3nMX-nwDTaaYQxtr_MKPuwKF9hujYlqU&amp;s=CmuQQvtCNHbWn7X9Zrjsrz92UDnyruY-lGkzJX9j4gE&amp;e=" moz-do-not-send="true">view it on GitHub</a>, or <a href="https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADF7AC2RO5ZLEGLEJJJUAMDX4Q6IHANCNFSM6AAAAAA4NPGYC4&amp;d=DwMCaQ&amp;c=CJqEzB1piLOyyvZjb8YUQw&amp;r=Hy7ijcc6pcMoP-QxZxtQH4-vodW_VGkrA9xiBc7InXk&amp;m=8Z3owTVaNZCsWPb8_BP8F5tA7zcWi2LG3nMX-nwDTaaYQxtr_MKPuwKF9hujYlqU&amp;s=qhnn74Z8lOGQS9yYc5qNrZt92fPpYwnoL8KImGAsbl8&amp;e=" moz-do-not-send="true">unsubscribe</a>.<br>
        You are receiving this because you were mentioned.<img src="https://github.com/notifications/beacon/ADF7AC2C2UUP2TWQWMQANIDX4Q6IHA5CNFSM6AAAAAA4NPGYC6WGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTHSGCM2.gif" alt="" moz-do-not-send="true" width="1" height="1"><span style="color: transparent; font-size: 0; display: none;
          visibility: hidden; overflow: hidden; opacity: 0; width: 0;
          height: 0; max-width: 0; max-height: 0; mso-hide: all">Message
          ID: <span>&lt;JeffersonLab/halld_recon/issues/745/1737589965</span><span>@</span><span>github</span><span>.</span><span>com&gt;</span></span></p>
      <script type="application/ld+json">[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/JeffersonLab/halld_recon/issues/745#issuecomment-1737589965",
"url": "https://github.com/JeffersonLab/halld_recon/issues/745#issuecomment-1737589965",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]</script>
    </blockquote>
    <br>
  </body>
</html>

--------------C6tMp2h70xLCNEf6PvGmpYpA--

**Comment by staylorjlab** [comment]
I'll take a look.

**Comment by staylorjlab** [comment]
The CCAL shower factory has a memory leak.  I found the location of the problem and am looking at finding a fix.

**Comment by staylorjlab** [comment]
This memory leak was fixed by https://github.com/JeffersonLab/halld_recon/pull/752
