### ISSUE TITLE
Plugin TrackingPulls has no root locks

### ISSUE THREAD

**Issue by aaust** [JeffersonLab/halld_recon#820]
After the reduction of the dependence on HistogramTools in #795 , the plugin [TrackingPulls](https://github.com/JeffersonLab/halld_recon/tree/master/src/plugins/monitoring/TrackingPulls) is missing the proper locks for multithreading. Thanks to @nsjarvis for pointing that out.

**Comment by aaust** [comment]
Addressed by #827

**Comment by nsjarvis** [comment]
Could we write a utility to scan plugins & check for missing rootlocks?
