### ISSUE TITLE
problems saving DC data in REST

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/halld_recon#91]
from Beni: 

So here again an example this time a 1to1 comparison between v00 and v01 for 
track candidate id=1 of event 49701366 in Run 41197 and all hypotheses

chargedTrack candidateId="1" jtag="" ptype="Positron"

v00: px="-0.0651044" py="-0.725847" pz="0.357643" t0="-2.881"  x0="0.139412" y0="0.0145783" z0="64.5425" 
**v00: hitlayers CDCrings="201062247" FDCplanes="0" /
v00: expectedhits expectedCDChits="28" expectedFDChits="0" measuredCDChits="22" measuredFDChits="0" /**
v00: dEdxDC NsampleCDC="17" NsampleFDC="0" dEdxCDC="1.00676" dEdxFDC="0"

v01: px="-0.0658771" py="-0.731998" pz="0.358403" t0="-12.1212" x0="0.14244" y0="0.0142421" z0="64.546" 
**v01: hitlayers CDCrings="0" FDCplanes="0" /
v01: expectedhits expectedCDChits="0" expectedFDChits="0" measuredCDChits="0" measuredFDChits="0" /**
v01: dEdxDC NsampleCDC="17" NsampleFDC="0" dEdxCDC="1.29769" dEdxFDC="0" 

chargedTrack candidateId="1" jtag="" ptype="Pi+"

v00: px="-0.0644569" py="-0.722373" pz="0.35598" t0="-2.9221" x0="0.136085" y0="0.0149767" z0="64.5414"
v00: hitlayers CDCrings="201062247" FDCplanes="0" /
v00: expectedhits expectedCDChits="28" expectedFDChits="0" measuredCDChits="22" measuredFDChits="0" /
v00: dEdxDC NsampleCDC="17" NsampleFDC="0" dEdxCDC="1.00774" dEdxFDC="0"

v01: px="-0.0652792" py="-0.728827" pz="0.356862" t0="-2.92895" x0="0.139352" y0="0.0146108" z0="64.544" 
v01: hitlayers CDCrings="201064295" FDCplanes="0" /
v01: expectedhits expectedCDChits="28" expectedFDChits="0" measuredCDChits="23" measuredFDChits="0" /
v01: dEdxDC NsampleCDC="17" NsampleFDC="0" dEdxCDC="1.2984" dEdxFDC="0" 

chargedTrack candidateId="1" jtag="" ptype="K+"

v00: px="-0.0646934" py="-0.723237" pz="0.356236" t0="-3.35947" x0="0.138882" y0="0.0146798" z0="64.5469"
**v00: hitlayers CDCrings="201062247" FDCplanes="0" /
v00: expectedhits expectedCDChits="28" expectedFDChits="0" measuredCDChits="22" measuredFDChits="0" /**
v00: dEdxDC NsampleCDC="17" NsampleFDC="0" dEdxCDC="1.00859" dEdxFDC="0"

v01: px="-0.065505" py="-0.72953" pz="0.357201" t0="-12.3043" x0="0.14205" y0="0.0143165" z0="64.5424"
**v01: hitlayers CDCrings="0" FDCplanes="0" /
v01: expectedhits expectedCDChits="0" expectedFDChits="0" measuredCDChits="0" measuredFDChits="0" /**
v01: dEdxDC NsampleCDC="17" NsampleFDC="0" dEdxCDC="1.29976" dEdxFDC="0"

chargedTrack candidateId="1" jtag="" ptype="Proton"

v00: px="-0.0657238" py="-0.731184" pz="0.357624" t0="-4.36118" x0="0.143318" y0="0.0141856" z0="64.5665"
v00: hitlayers CDCrings="201062247" FDCplanes="0" /
v00: expectedhits expectedCDChits="28" expectedFDChits="0" measuredCDChits="22" measuredFDChits="0" /
v00: dEdxDC NsampleCDC="17" NsampleFDC="0" dEdxCDC="1.00302" dEdxFDC="0"

v01: px="-0.0659817" py="-0.732647" pz="0.358342" t0="-4.40312" x0="0.144709" y0="0.014022" z0="64.562"
v01: hitlayers CDCrings="201064295" FDCplanes="0" /
v01: expectedhits expectedCDChits="28" expectedFDChits="0" measuredCDChits="23" measuredFDChits="0" /
v01: dEdxDC NsampleCDC="17" NsampleFDC="0" dEdxCDC="1.30116" dEdxFDC="0"

**Comment by staylorjlab** [comment]
book-keeping is fixed in the latest master
